name: Build and Create Releases

on:
  push:
    branches: [ development ]
    tags:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  test-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Run Unit Tests
        run: ./gradlew androidApp:testDebugUnitTest

  build-android:
    needs: test-android
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build Android AAB
        run: ./gradlew androidApp:bundleRelease --stacktrace --info
      - name: Build Android APK
        run: ./gradlew androidApp:assembleRelease --stacktrace --info
      - name: Verify APK & AAB files before renaming
        run: ls -R androidApp/build/outputs/
      - name: Rename APK for consistency
        run: mv androidApp/build/outputs/apk/release/androidApp-release-unsigned.apk androidApp/build/outputs/apk/release/androidApp-release.apk
      - name: Verify APK & AAB files after renaming
        run: ls -R androidApp/build/outputs/
      - name: Upload AAB as artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-aab
          path: androidApp/build/outputs/bundle/release/androidApp-release.aab
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: androidApp/build/outputs/apk/release/androidApp-release.apk
      - name: Upload full outputs folder (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: android-full-output

