name: Build and Create Releases

on:
  push:
    branches: [ development ]
    tags:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  build-android:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build Android AAB
        run: ./gradlew androidApp:bundleRelease

      - name: Build Android APK
        run: ./gradlew androidApp:assembleRelease

  create-release:
    if: startsWith(github.ref, 'refs/tags/v')
    permissions: write-all
    runs-on: ubuntu-latest
    needs: build-android
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  upload-assets:
    if: startsWith(github.ref, 'refs/tags/v')
    permissions: write-all
    runs-on: ubuntu-latest
    needs: create-release

    steps:
      - uses: actions/checkout@v4

      - name: Upload Release AAB Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: androidApp/release/androidApp-release.aab
          asset_name: toebeans-${{ github.ref_name }}.aab
          asset_content_type: application/x-authorware-bin

      - name: Upload Release APK Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: androidApp/build/outputs/apk/release/androidApp-release.apk
          asset_name: toebeans-${{ github.ref_name }}.apk
          asset_content_type: application/vnd.android.package-archive
